[project]
name = "dialoglite"
version = "1.2.1"
description = "Simple work hours and overtime tracking "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2wsgi>=1.10.10",
    "fastmcp>=3.3.1",
    "flask>=3.1.3",
    "flask-openapi3>=4.3.2",
    "flask-sqlalchemy>=3.1.1",
    "holidays>=0.93",
    "mcp[cli]>=1.27.1",
    "playwright>=1.58.0",
    "pydantic>=2.13.4",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.47.0",
]

[tool.uv]
package = false
